version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: 20.11.1
        PYTHON_VERSION: 3.11.5
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
